"""Public baseline interface for zkSEC."""

from .context import (
    SECURITY_CONTEXT_VERSION,
    known_adjacent_surfaces,
    known_surface_invariants,
    load_security_context,
)
from .routing import RoutedActionDecision, evaluate_adapter_action
from .build_mu_exec_from_ingest import (
    load_ir_grounding_facts,
    load_trace_proposal_facts,
    resolve_linkage_witness,
)
from .ingest_types import IRGroundingFact, LinkageWitness, TraceProposalFact
from .mu_exec import (
    MuExecGhidraGroundingFact,
    MuExecIngestBundle,
    MuExecLinkResolution,
    MuExecTraceProposalFact,
    MuExecWitness,
    build_mu_exec_witness,
    build_mu_exec_witness_from_ingest,
    evaluate_mu_exec_invariants,
    mu_exec_receipt_fields,
    normalize_mu_exec_ingest,
)
from .admissibility import (
    ALLOWED_ZOS_INBOUND_FIELDS,
    ARTIFACT_CLASSES,
    CAPABILITY_CLASSES,
    CHANNEL_CLASSES,
    FORBIDDEN_ZOS_AUTHORITY_FIELDS,
    PROPOSAL_STATES,
    RING_CLASSES,
    TRANSFORM_CLASSES,
    AdmissibilityDecision,
    AdmissibilityInput,
    AttackChainResult,
    AttackStep,
    DetectorSignal,
    OntologyDelta,
    UnifiedDetectorOutput,
    WitnessExpectation,
    ZOSBridgeResult,
    assess_ontology_surface,
    bridge_zos_proposal,
    evaluate_attack_chain,
    evaluate_transform_admissibility,
    evaluate_unified_detector,
)
from .security import (
    SecurityDecision,
    assess_action,
    assess_data_boundary,
    policy_receipt,
)
from .execution import AdapterExecutionDirective, build_execution_directive
from .reporting import execution_audit_record
from .adapters import (
    AdapterCheckResult,
    AdapterContract,
    AdapterActionCapability,
    AdapterCapabilityPolicy,
    validate_action_against_adapter,
    action_capability_policy,
    kant_zk_pastebin_contract,
    zos_server_contract,
)

__all__ = [
    "SECURITY_CONTEXT_VERSION",
    "known_adjacent_surfaces",
    "known_surface_invariants",
    "load_security_context",
    "ALLOWED_ZOS_INBOUND_FIELDS",
    "ARTIFACT_CLASSES",
    "CAPABILITY_CLASSES",
    "CHANNEL_CLASSES",
    "FORBIDDEN_ZOS_AUTHORITY_FIELDS",
    "PROPOSAL_STATES",
    "RING_CLASSES",
    "TRANSFORM_CLASSES",
    "DetectorSignal",
    "UnifiedDetectorOutput",
    "OntologyDelta",
    "WitnessExpectation",
    "ZOSBridgeResult",
    "AdmissibilityInput",
    "AdmissibilityDecision",
    "AttackStep",
    "AttackChainResult",
    "bridge_zos_proposal",
    "assess_ontology_surface",
    "evaluate_unified_detector",
    "evaluate_transform_admissibility",
    "evaluate_attack_chain",
    "SecurityDecision",
    "assess_action",
    "assess_data_boundary",
    "policy_receipt",
    "AdapterCheckResult",
    "AdapterContract",
    "AdapterActionCapability",
    "AdapterCapabilityPolicy",
    "action_capability_policy",
    "validate_action_against_adapter",
    "kant_zk_pastebin_contract",
    "zos_server_contract",
    "RoutedActionDecision",
    "evaluate_adapter_action",
    "TraceProposalFact",
    "IRGroundingFact",
    "LinkageWitness",
    "resolve_linkage_witness",
    "load_trace_proposal_facts",
    "load_ir_grounding_facts",
    "MuExecTraceProposalFact",
    "MuExecGhidraGroundingFact",
    "MuExecIngestBundle",
    "MuExecLinkResolution",
    "MuExecWitness",
    "build_mu_exec_witness",
    "build_mu_exec_witness_from_ingest",
    "evaluate_mu_exec_invariants",
    "mu_exec_receipt_fields",
    "normalize_mu_exec_ingest",
    "AdapterExecutionDirective",
    "build_execution_directive",
    "execution_audit_record",
]
